### ISSUE TITLE
Getting a license for this template such as MIT or GPL

### ISSUE THREAD

**Issue by ShadowedLight** [saroz/fifa-russia#1]
Hello, I really love your template and was wanting to use it, however, I am unable to use it as you don’t provide a license. I was wondering if you could possibly provide a license for the repository such as MIT to allow the template to be used freely.

https://choosealicense.com/no-permission/

**Comment by saroz** [comment]
Updated LICENSE as MIT. Apology for late update.
Thanks @ShadowedLight
